# ASP.NET Core

trigger:
- master

jobs:
- job: Test
  timeoutInMinutes: 0
  pool:
    vmImage: 'windows-2019'

  steps:

# TEST
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: 6.x

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: '**/*.csproj'


  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      projects: '**/*[Tt]ests/*.csproj'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/SilveR.IntegrationTests/bin/Debug/net6.0/ActualResults/*'
      archiveFile: '$(Build.ArtifactStagingDirectory)/Test-Results.zip'


# BUILD LITE VERSION
  - script: 'dotnet clean'
    displayName: Clean Build

  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: 'publish'
      arguments: '--output $(Build.ArtifactStagingDirectory) -r win-x64'
      zipAfterPublish: true

  - task: CopyFiles@2
    inputs:
      contents: '*.zip'
      targetFolder: '$(Build.ArtifactStagingDirectory)/'

  - task: CmdLine@2
    inputs:
      script: 'ren $(Build.ArtifactStagingDirectory)\SilveR.zip InVivoStat-win-x64-test-only.zip'

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: 'drop'

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: github
      repositoryName: robalexclark/SilveR
      action: edit
      target: 'master'
      tagSource: manual
      tag: '4.6.0'
      title: '4.6.0'
      assetUploadMode: 'replace'
      isPreRelease: true
      isDraft: false
      
      

- job: Windows
  dependsOn: Test
  pool:
    vmImage: 'windows-2019'

  steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: 5.x

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: 6.x

  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'

  - script: dotnet tool install ElectronNET.CLI -g
    displayName: Install Electron.Net CLI

  - script: 'dotnet clean'
    displayName: Clean Build

  - script: electronize build /target win
    workingDirectory: ./SilveR
    displayName: Build for Win-x64

  - script: 'xcopy $(Build.SourcesDirectory)\SilveR\bin\Desktop\"InVivoStat Setup 4.6.0.exe" $(Build.ArtifactStagingDirectory)'
    displayName: Copy InVivoStat Setup 4.6.0.exe

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)\SilveR\bin\Desktop\InVivoStat Setup 4.6.0.exe'
      ArtifactName: 'drop'

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: github
      repositoryName: robalexclark/SilveR
      action: edit
      target: 'master'
      tagSource: manual
      tag: '4.6.0'
      title: '4.6.0'
      assetUploadMode: 'replace'
      isPreRelease: true
      isDraft: false



- job: Linux
  dependsOn: Test
  pool:
    vmImage: 'ubuntu-18.04'

  steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: 5.x

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: 6.x

  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'

  - script: dotnet tool install ElectronNET.CLI -g
    displayName: Install Electron.Net CLI

  - script: sudo npm install electron-builder --global
    displayName: Install electron builder

  - script: sudo chown -R $(whoami) ~/.npm
    displayName: Reset permissions

  - script: electronize build /target linux
    workingDirectory: ./SilveR
    displayName: Build for Linux

  - script: 'cp $(Build.SourcesDirectory)/SilveR/bin/Desktop/InVivoStat-4.6.0.AppImage $(Build.ArtifactStagingDirectory)'  
    displayName: Copy InVivoStat Setup 4.6.0.AppImage

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/InVivoStat-4.6.0.AppImage'
      ArtifactName: 'drop'

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: github
      repositoryName: robalexclark/SilveR
      action: edit
      target: 'master'
      tagSource: manual
      tag: '4.6.0'
      title: '4.6.0'
      assetUploadMode: 'replace'
      isPreRelease: true
      isDraft: false



- job: MacOS
  dependsOn: Test
  pool:
    vmImage: 'macOS-10.15'

  steps:
  
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: 5.x

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: 6.x

  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'

  - script: dotnet tool install ElectronNET.CLI -g
    displayName: Install Electron.Net CLI

  - script: sudo npm install electron-builder --global
    displayName: Install electron-builder

  - script: electronize build /target osx 
    workingDirectory: ./SilveR
    displayName: Build for MacOS

  - script: 'cp $(Build.SourcesDirectory)/SilveR/bin/Desktop/InVivoStat-4.6.0.dmg $(Build.ArtifactStagingDirectory)'
    displayName: Copy InVivoStat Setup 4.6.0.dmg

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/InVivoStat-4.6.0.dmg'
      ArtifactName: 'drop'

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: github
      repositoryName: robalexclark/SilveR
      action: edit
      target: 'master'
      tagSource: manual
      tag: '4.6.0'
      title: '4.6.0'
      assetUploadMode: 'replace'
      isPreRelease: true
      isDraft: false
