#===================================================================================================================
#R Libraries

suppressWarnings(library(multcomp))
suppressWarnings(library(R2HTML))

#===================================================================================================================
# retrieve args
Args <- commandArgs(TRUE)

testtype <-Args[4]
#Currently the only option included:
testtype <- "UsePValues"

test <- Args[5]
sigLevel <- as.numeric(Args[6])

if (testtype == "UsePValues") {
	pValues <- Args[4]
}

if (testtype == "UseDataSet") {
	statdata <- read.csv(Args[3], header=TRUE, sep=",")
}

#source(paste(getwd(),"/Common_Functions.R", sep=""))

#Print args
if (Diplayargs == "Y"){
	print(Args)
}

#===================================================================================================================
#Setup the html file and associated css file
htmlFile <- sub(".csv", ".html", Args[3]); #determine the file name of the html file
HTMLSetFile(file=htmlFile) 
cssFile <- "r2html.css"
cssFile <- paste("'",cssFile,"'", sep="") #need to enclose in quotes when path has spaces in it
HTMLCSS(CSSfile = cssFile)

#===================================================================================================================
#Output HTML header
Title <-paste(branding, " P-Value Adjustment", sep="")
HTML.title(Title, HR = 1, align = "left")

add<-paste(c("The input p-values for this module should be unadjusted p-values. These unadjusted p-values are adjusted using "), test, "'s multiple comparison procedure.", sep="")
HTML(add, align="left")

#Bate and Clark comment
HTML(refxx, align="left")	

HTML.title("Results", HR=2, align="left")

#===================================================================================================================
#Seperate out the p-values
#===================================================================================================================
if (testtype == "UseDataSet") {
	HTML("If the dataset containing the p-values, used as the input into this module, were generated by the Single Measures Parametric Analysis module or Repeated Measures Parametric Analysis module, you should confirm the correct set of p-values have been uploaded.", align="left")

	#STB Jan 2017  - reorder dataset to aid mergign at end
	statdata2 <- statdata[order(statdata$pivs_hyphen_ivsvalue),] 
	statdata<- statdata2
	compz<-data.frame(statdata$Comparison)
	pValues <- statdata$pivs_hyphen_ivsvalue[1]

	if(dim(statdata)[1]>1) 	{
		for (i in 2:dim(statdata)[1])	{
			pValues <- paste(pValues , " , " ,statdata$pivs_hyphen_ivsvalue[i], sep = "")
		}
		tempChanges <-strsplit(pValues, ",")
	} else {
		tempChanges <-pValues
	}
}

if (testtype == "UsePValues")
{
	tempChanges <-strsplit(pValues, ",")
}

txtexpectedChanges <- c("")
expectedChanges <- numeric(0)
lessindex<-1
lessindex2<-1

for(i in 1:length(tempChanges[[1]]))  { 
	txtexpectedChanges [length(txtexpectedChanges )+1]=(tempChanges[[1]][i]) 
}

for (i in 1:length(tempChanges[[1]]))  {
	if (txtexpectedChanges[i+1]=="<0.001")  {
		txtexpectedChanges[i+1]="0.00099"
		lessindex=2
	}
	if (txtexpectedChanges[i+1]=="<0.0001")  {
		txtexpectedChanges[i+1]="0.000099"
		lessindex2=2
	}
	if (txtexpectedChanges[i+1]=="< 0.001")  {
		txtexpectedChanges[i+1]="0.00099"
		lessindex=2
	}
	if (txtexpectedChanges[i+1]=="< 0.0001")  {
		txtexpectedChanges[i+1]="0.000099"
		lessindex2=2
	}

}

expectedChanges<-as.numeric(txtexpectedChanges)
expectedChanges<-sort(expectedChanges)

#Re-order txt values
expectedChanges3<-as.numeric(txtexpectedChanges)
expectedChanges2<-na.omit(expectedChanges3)
tempdata<-data.frame(expectedChanges2,tempChanges)
colnames(tempdata)<-c("num","txt")
tempdata2<-tempdata[with(tempdata,order(num)),]
tempdata3<-tempdata2$txt

pvalus<-c(0)

for (i in 1:length(expectedChanges)) {
	pvalus[i]=expectedChanges[i]
}

#===================================================================================================================
#Code for all tests
#===================================================================================================================
#All pairwise test options

allPairwiseTestText = test
if (allPairwiseTestText=="Holm") {
	allPairwiseTest= "holm"
} else if (allPairwiseTestText=="Hochberg") {
	allPairwiseTest= "hochberg"
} else if (allPairwiseTestText=="Hommel") {
	allPairwiseTest= "hommel"
} else if (allPairwiseTestText=="Bonferroni") {
	allPairwiseTest= "bonferroni"
} else if (allPairwiseTestText=="Benjamini-Hochberg") {
	allPairwiseTest= "BH"
}

#Calculating the adjusted p-values
pvals<-p.adjust(pvalus, method = allPairwiseTest)

#Table for output
table<-matrix(nrow=length(pvals), ncol=1)
for ( i in 1:length(pvals)) {
	table[i,1]=format(round(pvals[i], 4), nsmall=4, scientific=FALSE)
}

for (i in 1:length(pvals)) {
#STB march 2011 formatting p-values p<0.0001 
	if (pvals[i]<0.0001) {
		# table[i,2]<-"<0.0001"
		table[i,1]=format(round(0.0001, 4), nsmall=4, scientific=FALSE)
		table[i,1]<- paste("<",table[i,1])
	}
}

#STB Jan 2017
if (testtype == "UseDataSet") {
	table2<-data.frame(compz,tempdata3,table)
	colnames(table2)<-c("Comparison","Unadjusted p-value" , "Adjusted p-value")
} else {
	table2<-data.frame(tempdata3,table)
	colnames(table2)<-c( "Unadjusted p-value" , "Adjusted p-value")
}
HTML(table2, classfirstline="second", align="left", row.names="FALSE")

if (lessindex==2 && lessindex2==1) {
	HTML("WARNING: You have entered unadjusted p-value(s) of the form <0.001. For the purposes of the numerical calculation this value has been replaced with 0.00099 and hence the adjusted p-value(s) may be unduly conservative.", align="left")
}
if (lessindex2==2 && lessindex==1) {
	HTML("WARNING: You have entered unadjusted p-value(s) of the form <0.0001. For the purposes of the numerical calculation this value has been replaced with 0.000099 and hence the adjusted p-value(s) may be unduly conservative.", align="left")
}
if (lessindex==2 && lessindex2==2) {
	HTML("WARNING: You have entered unadjusted p-values of the form <0.001 and <0.0001. For the purposes of the numerical calculation these values has been replaced with 0.00099 and 0.000099 respectively and hence the adjusted p-values may be unduly conservative.", align="left")
}

#===================================================================================================================
#Conclusions
#===================================================================================================================
HTML.title("Conclusions", HR=2, align="left")

add<-paste(c(""))
inte<-1
for(i in 1:(dim(table2)[1])) {
	if (pvals[i] <= (sigLevel)) {
		inte<-inte+1
	}
}
inteperm<-inte
index<-1
for(i in 1:(dim(table2)[1])) {
	if (pvals[i] <= (sigLevel) & inte==2) {
		add<-paste(add, "The unadjusted p-value ", table2[i,1], " is statistically significant at the ", 100*(sigLevel), "% level, using ", test, "'s multiple comparison procedure.", sep="")
	} 
}

if (inte>2) {
	add<-paste(add, "The unadjusted p-values ", sep="")
}

for(i in 1:(dim(table2)[1])) {
	if (pvals[i] <= (sigLevel) && inte>=3) {
		if (index<=inteperm-3) {
			add<-paste(add, table2[i,1], ", ", sep="")
		} 
		if (index==inteperm-2) {
			add<-paste(add, table2[i,1], " and ", sep="")
		} 
		if (index==inteperm-1) {
			add<-paste(add, table2[i,1], " ", sep="")
		}
		index=index+1
	}
}

if (inte>2) {
	add<-paste(add, "are statistically significant at the  ", 100*(sigLevel), "% level, using ", test, "'s multiple comparison procedure.", sep="")
}

if (inte==1) {
	if (dim(table2)[1] >1) {
		add<-paste(add, " There are no statistically significant p-values at the ", 100*(sigLevel), "% level, using ", test, "'s multiple comparison procedure.", sep="")
	} else {
		add<-paste(add, " The p-value is not statistically significant at the ", 100*(sigLevel), "% level, using ", test, "'s multiple comparison procedure.", sep="")
	}
}
HTML(add, align="left")

#===================================================================================================================
#References
#===================================================================================================================
Ref_list<-R_refs()

HTML.title("Statistical references", HR=2, align="left")
HTML(Ref_list$BateClark_ref, align="left")

if (allPairwiseTest== "BH" ) {
	HTML("Benjamini Y and Hochberg Y. (1995). Controlling the false discovery rate: a practical and powerful approach to multiple testing. 	Journal of the Royal Statistical Society Series B, 57, 289-300. ", align="left")
}
if (allPairwiseTest== "bonferroni" ) {
	HTML("Bonferroni CE (1936). Teoria statistica delle classi e calcolo delle probabilita.  Pubblicazioni del R Istituto Superiore di Scienze 	Economiche e Commerciali di Firenze, 8, 3-62.", align="left")
}
if (allPairwiseTest== "hochberg" ) {
	HTML("Hochberg Y. (1988). A sharper Bonferroni procedure for multiple tests of significance. Biometrika, 75, 800-803.", align="left")
}
if (allPairwiseTest== "holm" ) {
	HTML("Holm S. (1979). A simple sequentially rejective multiple test procedure. Scandinavian Journal of Statistics, 6, 65-70.", 	align="left")
} 
if (allPairwiseTest== "hommel" ) {
	HTML("Hommel G. (1988). A stagewise rejective multiple test procedure based on a modified Bonferroni test. Biometrika, 75, 383-386.", align="left")
}

HTML.title("R references", HR=2, align="left")
HTML(Ref_list$R_ref , align="left")
HTML(Ref_list$R2HTML_ref, align="left")
HTML(Ref_list$multcomp_ref, align="left")

#===================================================================================================================
#Show arguments
#===================================================================================================================
HTML.title("Analysis options", HR=2, align="left")

if (testtype== "UsePValues") {
	HTML(paste("Analysis approach used: User supplied p-values"), align="left")
} else {
	HTML(paste("Analysis approach used: Use dataset to input p-values"), align="left")
}

HTML(paste("Multiple comparison adjustment used: ", test, sep=""), align="left")
if (testtype== "UsePValues") {
	HTML(paste("User entered p-values: ", pValues, sep=""), align="left")
}
HTML(paste("Significance level: ", sigLevel, sep=""), align="left")

