#===================================================================================================================
#R Libraries

suppressWarnings(library(multcomp))
suppressWarnings(library(R2HTML))
#===================================================================================================================


#===================================================================================================================
# retrieve args
Args <- commandArgs(TRUE)

#Read in data

pValues <- Args[4]
test <- Args[5]
sigLevel <- as.numeric(Args[6])

testtype <- "UsePValues"
#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#===================================================================================================
#Setup the html file and associated css file
htmlFile <- sub(".csv", ".html", Args[3]);
#determine the file name of the html file
HTMLSetFile(file = htmlFile)
.HTML.file = htmlFile


#Output HTML header

HTML.title("<bf>P-Value Adjustment", HR = 1, align = "left")
add <- paste(c("The input p-values for this module should be unadjusted p-values. These unadjusted p-values are adjusted using "), test, sep = "")
add <- paste(add, "'s multiple comparison procedure.", sep = "")
HTML.title("</bf> ", HR = 2, align = "left")
HTML.title(add, HR = 0, align = "left")

#Bate and Clark comment
HTML.title("<bf> ", HR = 2, align = "left")
HTML.title(refxx, HR = 0, align = "left")

HTMLbr()
HTML.title("<bf>Results", HR = 2, align = "left")

#===================================================================================================

#Seperate out the p-values
if (testtype == "UseDataSet") {
    HTML.title("</bf> ", HR = 2, align = "left")
    HTML.title("If the dataset containing the p-values, used as the input into this module, were generated by the Single Measures Parametric Analysis module or Repeated Measures Parametric Analysis module, you should confirm the correct set of p-values have been uploaded.", HR = 0, align = "left")

    pValues <- statdata$pivs_hyphen_ivsvalue[1]

    if (dim(statdata)[1] > 1) {
        for (i in 2:dim(statdata)[1]) {
            pValues <- paste(pValues, " , ", statdata$pivs_hyphen_ivsvalue[i], sep = "")
        }
        tempChanges <- strsplit(pValues, ",")
    } else {
        tempChanges <- pValues
    }
}

if (testtype == "UsePValues") {
    tempChanges <- strsplit(pValues, ",")
}

txtexpectedChanges <- c("")
expectedChanges <- numeric(0)
lessindex <- 1
lessindex2 <- 1

for (i in 1:length(tempChanges[[1]])) {
    txtexpectedChanges[length(txtexpectedChanges) + 1] = (tempChanges[[1]][i])
}

for (i in 1:length(tempChanges[[1]])) {
    if (txtexpectedChanges[i + 1] == "<0.001") {
        txtexpectedChanges[i + 1] = "0.00099"
        lessindex = 2
    }
    if (txtexpectedChanges[i + 1] == "<0.0001") {
        txtexpectedChanges[i + 1] = "0.000099"
        lessindex2 = 2
    }
    if (txtexpectedChanges[i + 1] == "< 0.001") {
        txtexpectedChanges[i + 1] = "0.00099"
        lessindex = 2
    }
    if (txtexpectedChanges[i + 1] == "< 0.0001") {
        txtexpectedChanges[i + 1] = "0.000099"
        lessindex2 = 2
    }

}

expectedChanges <- as.numeric(txtexpectedChanges)
expectedChanges <- sort(expectedChanges)

#Re-order txt values
expectedChanges3 <- as.numeric(txtexpectedChanges)
expectedChanges2 <- na.omit(expectedChanges3)
tempdata <- data.frame(expectedChanges2, tempChanges)
colnames(tempdata) <- c("num", "txt")
tempdata2 <- tempdata[with(tempdata, order(num)),]
tempdata3 <- tempdata2$txt

pvalus <- c(0)

for (i in 1:length(expectedChanges)) {
    pvalus[i] = expectedChanges[i]
}


#code for test

#All pairwise test options

allPairwiseTestText = test
if (allPairwiseTestText == "Holm") {
    allPairwiseTest = "holm"
} else if (allPairwiseTestText == "Hochberg") {
    allPairwiseTest = "hochberg"
} else if (allPairwiseTestText == "Hommel") {
    allPairwiseTest = "hommel"
} else if (allPairwiseTestText == "Bonferroni") {
    allPairwiseTest = "bonferroni"
} else if (allPairwiseTestText == "Benjamini-Hochberg") {
    allPairwiseTest = "BH"
}

#Calculating the adjusted p-values
pvals <- p.adjust(pvalus, method = allPairwiseTest)


#Table for output

table <- matrix(nrow = length(pvals), ncol = 2)
for (i in 1:length(pvals)) {
    table[i, 2] = format(round(pvals[i], 4), nsmall = 4, scientific = FALSE)
}

for (i in 1:length(pvals)) {
    #STB march 2011 formatting p-values p<0.0001 
    if (pvals[i] < 0.0001) {
        #		table[i,2]<-"<0.0001"
        table[i, 2] = format(round(0.0001, 4), nsmall = 4, scientific = FALSE)
        table[i, 2] <- paste("<", table[i, 2])
    }
}

table2 <- data.frame(tempdata3, table)

colnames(table2) <- c("Unadjusted p-value", " ", "Adjusted p-value")

HTML(table2, classfirstline = "second", align = "left")

if (lessindex == 2 && lessindex2 == 1) {
    message <- c("WARNING: You have entered unadjusted p-value(s) of the form <0.001. For the purposes of the numerical calculation this value has been replaced with 0.00099 and hence the adjusted p-value(s) may be unduly conservative.")

    HTML.title("</bf> ", HR = 2, align = "left")
    HTML.title(message, HR = 0, align = "left")

}
if (lessindex2 == 2 && lessindex == 1) {
    message <- c("WARNING: You have entered unadjusted p-value(s) of the form <0.0001. For the purposes of the numerical calculation this value has been replaced with 0.000099 and hence the adjusted p-value(s) may be unduly conservative.")

    HTML.title("</bf> ", HR = 2, align = "left")
    HTML.title(message, HR = 0, align = "left")
}
if (lessindex == 2 && lessindex2 == 2) {
    message <- c("WARNING: You have entered unadjusted p-values of the form <0.001 and <0.0001. For the purposes of the numerical calculation these values has been replaced with 0.00099 and 0.000099 respectively and hence the adjusted p-values may be unduly conservative.")
    HTML.title("</bf> ", HR = 2, align = "left")
    HTML.title(message, HR = 0, align = "left")
}



#Conclusions

HTMLbr()
HTML.title("<bf>Conclusions", HR = 2, align = "left")

#format p-values for comment
#table2[,1]


add <- paste(c(""))
inte <- 1
for (i in 1:(dim(table2)[1])) {
    if (pvals[i] <= (sigLevel)) {
        inte <- inte + 1
    }
}
inteperm <- inte
index <- 1
for (i in 1:(dim(table2)[1])) {
    if (pvals[i] <= (sigLevel) & inte == 2) {
        add <- paste(add, "The unadjusted p-value ", sep = "")
        add <- paste(add, table2[i, 1], sep = "")
        add <- paste(add, " is statistically significant at the ", sep = "")
        add <- paste(add, 100 * (sigLevel), sep = "")
        add <- paste(add, "% level, using ", sep = "")
        add <- paste(add, test, sep = "")
        add <- paste(add, "'s multiple comparison procedure.", sep = "")
    }
}

if (inte > 2) {
    add <- paste(add, "The unadjusted p-values ", sep = "")
}

for (i in 1:(dim(table2)[1])) {
    if (pvals[i] <= (sigLevel) && inte >= 3) {
        if (index <= inteperm - 3) {
            add <- paste(add, table2[i, 1], sep = "")
            add <- paste(add, ", ", sep = "")
        }
        if (index == inteperm - 2) {
            add <- paste(add, table2[i, 1], sep = "")
            add <- paste(add, " and ", sep = "")
        }
        if (index == inteperm - 1) {
            add <- paste(add, table2[i, 1], sep = "")
            add <- paste(add, " ", sep = "")
        }
        index = index + 1
    }
}

if (inte > 2) {
    add <- paste(add, "are statistically significant at the  ", sep = "")
    add <- paste(add, 100 * (sigLevel), sep = "")
    add <- paste(add, "% level, using ", sep = "")
    add <- paste(add, test, sep = "")
    add <- paste(add, "'s multiple comparison procedure.", sep = "")
}

if (inte == 1) {
    if (dim(table2)[1] > 1) {
        add <- paste(add, " There are no statistically significant p-values at the ", sep = "")
        add <- paste(add, 100 * (sigLevel), sep = "")
        add <- paste(add, "% level, using ", sep = "")
        add <- paste(add, test, sep = "")
        add <- paste(add, "'s multiple comparison procedure.", sep = "")
    } else {
        add <- paste(add, " The p-value is not statistically significant at the ", sep = "")
        add <- paste(add, 100 * (sigLevel), sep = "")
        add <- paste(add, "% level, using ", sep = "")
        add <- paste(add, test, sep = "")
        add <- paste(add, "'s multiple comparison procedure.", sep = "")
    }
}

HTML.title("</bf> ", HR = 2, align = "left")
HTML.title(add, HR = 0, align = "left")


#----------------------------------------------------------------------------------------------------------
#References
#----------------------------------------------------------------------------------------------------------
Ref_list <- R_refs()

HTMLbr()
HTML.title("<bf>Statistical references", HR = 2, align = "left")

HTML.title("<bf> ", HR = 2, align = "left")
HTML.title(Ref_list$BateClark_ref, HR = 0, align = "left")

if (allPairwiseTest == "BH") {
    HTML.title("<bf> ", HR = 2, align = "left")
    HTML.title("<bf>Benjamini Y and Hochberg Y. (1995). Controlling the false discovery rate: a practical and powerful approach to multiple testing. 	Journal of the Royal Statistical Society Series B, 57, 289-300. ", HR = 0, align = "left")
}

if (allPairwiseTest == "bonferroni") {
    HTML.title("<bf> ", HR = 2, align = "left")
    HTML.title("<bf>Bonferroni CE (1936). Teoria statistica delle classi e calcolo delle probabilita.  Pubblicazioni del R Istituto Superiore di Scienze 	Economiche e Commerciali di Firenze, 8, 3-62.", HR = 0, align = "left")
}

if (allPairwiseTest == "hochberg") {
    HTML.title("<bf> ", HR = 2, align = "left")
    HTML.title("<bf>Hochberg Y. (1988). A sharper Bonferroni procedure for multiple tests of significance. Biometrika, 75, 800-803.", HR = 0, align = "left")
}
if (allPairwiseTest == "holm") {
    HTML.title("<bf> ", HR = 2, align = "left")
    HTML.title("<bf>Holm S. (1979). A simple sequentially rejective multiple test procedure. Scandinavian Journal of Statistics, 6, 65-70.", HR = 0, align = "left")
}

if (allPairwiseTest == "hommel") {
    HTML.title("<bf> ", HR = 2, align = "left")
    HTML.title("<bf>Hommel G. (1988). A stagewise rejective multiple test procedure based on a modified Bonferroni test. Biometrika, 75, 383-386.", HR = 0, align = "left")
}

HTMLbr()
HTML.title("<bf>R references", HR = 2, align = "left")

HTML.title("<bf> ", HR = 2, align = "left")
HTML.title(Ref_list$R_ref, HR = 0, align = "left")

HTML.title("<bf> ", HR = 2, align = "left")
HTML.title(Ref_list$R2HTML_ref, HR = 0, align = "left")

HTML.title("<bf> ", HR = 2, align = "left")
HTML.title(Ref_list$multcomp_ref, HR = 0, align = "left")



