options(install.packages.check.source="no")
install.packages("R2HTML",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("ggplot2",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("ggrepel",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("plyr",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("reshape",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("GGally",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("proto",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("mvtnorm",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("coin",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("Exact",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("dplyr",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("multcompView",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("car",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("lsmeans",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("ggdendro",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("BiocManager",repos = "https://www.stats.bris.ac.uk/R/")
BiocManager::install("mixOmics")
install.packages("contrast")


install.packages("bitops",repos = "https://www.stats.bris.ac.uk/R/", version="1.0-6")
install.packages("caTools",repos = "https://www.stats.bris.ac.uk/R/", version="1.17.1.2")
install.packages("cluster",repos = "https://www.stats.bris.ac.uk/R/", version="2.1.0")
install.packages("gdata",repos = "https://www.stats.bris.ac.uk/R/", version="2.18.0")
install.packages("gplots",repos = "https://www.stats.bris.ac.uk/R/", version="0.8.1")
install.packages("gtools",repos = "https://www.stats.bris.ac.uk/R/", version="3.0.1.1")
install.packages("lattice",repos = "https://www.stats.bris.ac.uk/R/", version="0.20-38")
install.packages("gsl",repos = "https://www.stats.bris.ac.uk/R/", version="2.1-6")
install.packages("MBESS",repos = "https://www.stats.bris.ac.uk/R/", version="4.6.0")
install.packages("multcomp",repos = "https://www.stats.bris.ac.uk/R/", version=" 1.4-10")
install.packages("nlme",repos = "https://www.stats.bris.ac.uk/R/", version="3.1-137")
install.packages("pls",repos = "https://www.stats.bris.ac.uk/R/", version="2.7-1")
install.packages("RColorBrewer",repos = "https://www.stats.bris.ac.uk/R/", version="1.1-2")
install.packages("scales",repos = "https://www.stats.bris.ac.uk/R/", version="1.0.0")
install.packages("survival",repos = "https://www.stats.bris.ac.uk/R/", version="2.44-1.1")
install.packages("modeltools",repos = "https://www.stats.bris.ac.uk/R/", version="0.2-22")