options(install.packages.check.source="no")

install.packages("R2HTML",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("ggplot2",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("ggrepel",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("plyr",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("reshape",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("GGally",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("proto",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("mvtnorm",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("coin",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("Exact",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("dplyr",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("multcompView",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("car",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("lsmeans",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("ggdendro",repos = "https://www.stats.bris.ac.uk/R/")
install.packages("BiocManager",repos = "https://www.stats.bris.ac.uk/R/")
BiocManager::install("mixOmics")
install.packages("contrast")
