install.packages("R2HTML", repo="https://www.stats.bris.ac.uk/R/")
install.packages("ggplot2", repo="https://www.stats.bris.ac.uk/R/")
install.packages("ggrepel", repo="https://www.stats.bris.ac.uk/R/")
install.packages("plyr", repo="https://www.stats.bris.ac.uk/R/")
install.packages("reshape", repo="https://www.stats.bris.ac.uk/R/")
install.packages("GGally", repo="https://www.stats.bris.ac.uk/R/")
install.packages("proto", repo="https://www.stats.bris.ac.uk/R/")
install.packages("mvtnorm", repo="https://www.stats.bris.ac.uk/R/")
install.packages("coin", repo="https://www.stats.bris.ac.uk/R/")
install.packages("Exact", repo="https://www.stats.bris.ac.uk/R/")
install.packages("dplyr", repo="https://www.stats.bris.ac.uk/R/")
install.packages("multcompView", repo="https://www.stats.bris.ac.uk/R/")
install.packages("car", repo="https://www.stats.bris.ac.uk/R/")
install.packages("lsmeans", repo="https://www.stats.bris.ac.uk/R/")
install.packages("ggdendro", repo="https://www.stats.bris.ac.uk/R/")
install.packages("BiocManager", repo="https://www.stats.bris.ac.uk/R/")
BiocManager::install("mixOmics")
install.packages("contrast", repo="https://www.stats.bris.ac.uk/R/")
